const fs = require('fs');
const path = require('path');

const appPath = path.join(process.cwd(), 'src/App.tsx');
const content = fs.readFileSync(appPath, 'utf8');
const lines = content.split('\n');

// 1. Get imports block and update relative paths since we are moving from src/ to src/hooks/
let importsBlock = lines.slice(0, 248).join('\n');
importsBlock = importsBlock.replace(/(from\s+['"])(\.\/)([^'"]+['"])/g, '$1../$3');
// Fix layoutUtils import as it is in utils
importsBlock = importsBlock.replace(/\.\.\/utils\/layoutUtils/g, '../utils/layoutUtils');

// 2. Get body block (lines 250 to 4544, keeping in mind 0-based index)
// Line 250 is index 249. Line 4544 is index 4543.
const bodyLines = lines.slice(249, 4544);
const bodyText = bodyLines.join('\n');

// 3. Automatically detect declared variables, setters, and functions using regex
const declaredNames = new Set();

// Find useState definitions: const [x, setX] = useState...
const useStateRegex = /const\s+\[\s*([a-zA-Z0-9_]+)\s*,\s*([a-zA-Z0-9_]+)\s*\]\s*=\s*useState/g;
let match;
while ((match = useStateRegex.exec(bodyText)) !== null) {
  declaredNames.add(match[1]);
  declaredNames.add(match[2]);
}

// Find useMemo, useRef, useSearchParams, useNavigate, etc.
const hookRegex = /const\s+([a-zA-Z0-9_]+)\s*=\s*(?:useMemo|useRef|useCallback|useNavigate|useSearchParams|useTranslation|useTheme|useCalendar)/g;
while ((match = hookRegex.exec(bodyText)) !== null) {
  declaredNames.add(match[1]);
}

// Find standard variable assignments at root level of function (e.g. const isAdminUser = ...)
// Only match variables at the top level indentation of the function (2 spaces)
const rootVarRegex = /^[ ]{2}const\s+([a-zA-Z0-9_]+)\s*=/gm;
while ((match = rootVarRegex.exec(bodyText)) !== null) {
  declaredNames.add(match[1]);
}

// Find function declarations at root level (e.g. const showNotification = ...)
const rootFuncRegex = /^[ ]{2}const\s+([a-zA-Z0-9_]+)\s*=\s*(?:async\s*)?(?:\([^)]*\)|[a-zA-Z0-9_]+)\s*=>/gm;
while ((match = rootFuncRegex.exec(bodyText)) !== null) {
  declaredNames.add(match[1]);
}

const standardFuncRegex = /^[ ]{2}function\s+([a-zA-Z0-9_]+)/gm;
while ((match = standardFuncRegex.exec(bodyText)) !== null) {
  declaredNames.add(match[1]);
}

// Add specifically known variables to ensure they are returned
const manualNames = [
  'theme', 'toggleTheme', 'isAuthenticated', 'language', 'setLanguage', 'toggleLanguage',
  't', 'dir', 'isAdminUser', 'currentProviderName', 'currentUserName', 'calendarType',
  'setCalendarType', 'toggleCalendarType', 'allReviews', 'setAllReviews'
];
manualNames.forEach(name => declaredNames.add(name));

const sortedNames = Array.from(declaredNames).sort();

// Create the complete custom hook content
const hookContent = `// This file is auto-generated by refactoring process to maintain type safety and modularity
${importsBlock}

export function useAppState() {
  const syncLockRef = React.useRef(false);

${bodyText}

  return {
${sortedNames.map(name => `    ${name}`).join(',\n')}
  };
}
`;

// Ensure hooks directory exists
const hookDir = path.join(process.cwd(), 'src/hooks');
if (!fs.existsSync(hookDir)) {
  fs.mkdirSync(hookDir, { recursive: true });
}

fs.writeFileSync(path.join(hookDir, 'useAppState.ts'), hookContent, 'utf8');
console.log('Successfully wrote src/hooks/useAppState.ts with', sortedNames.length, 'returned variables.');
