name: Sync Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync to Organization Repo
        uses: repo-sync/github-sync@v2
        with:
          target_repo_token: ${{ secrets.LAILAH_CS2_SYNC }}
          destination_repo: "Lailah-Plat/lailah_CS2"
          destination_branch: "main"
