name: Sync Repositories

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Organization Repo
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "Kas30/lailah_CS"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.LAILAH_CS2_SYNC }}
